import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import CommsNotifier from "./components/CommsNotifier";
import CommsProvider from "./components/CommsProvider";
import ForumProvider from "./components/ForumProvider";
import PresenceProvider from "./components/PresenceProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <PresenceProvider>
            <ForumProvider>
              <CommsProvider>
                {children}
                {/* Any page: a message that arrives pops up (desktop) or opens comms (mobile). */}
                <CommsNotifier />
              </CommsProvider>
            </ForumProvider>
          </PresenceProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
